name: PEP8 Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testing:
    name: Test w/ pylint & flake
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install libs
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint

      - name: Test flake8
        run: flake8 .

      - name: Test pylint
        run: find . -name "*.py" | xargs pylint
